issues:
  exclude-rules:
    - linters: [gosimple]
      path: values/drop_test.go # see the note in the file
      text: "S1005:"

    # go generate introduces these
    - path: expressions/scanner.go
      linters: [deadcode, unused, varcheck]
linters:
  enable:
    - gofmt
